config/urls.py
from django.contrib import admin
from django.urls import include, path

# from django.conf import settings
# from django.conf.urls.static import static
from ratings import views as ratings_views

urlpatterns = [
    path("", include("pages.urls")),
    path("accounts/", include("allauth.urls")),
    path("admin/", admin.site.urls),
    path("movies/", include("movies.urls")),
    path("rate/movie/", ratings_views.rate_movie_view),
]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path
from . import views

app_name = "movies"

urlpatterns = [
    path("", views.movie_list_view, name="list"),
    path("infinite/", views.movie_infinite_rating_view, name="infinite"),
    path("popular/", views.movie_popular_view, name="popular"),
    path("<int:pk>/", views.movie_detail_view, name="detail"),
]

pages/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.index_page_view, name="index"),
]

templates/_base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{% block titlte %}Recommender Engine{% endblock titlte %}</title>
    {# css files #}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    {# Bootstrap cdn link #}
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    {# htmx #}
  <script src="https://unpkg.com/htmx.org@2.0.1" integrity="sha384-QWGpdj554B4ETpJJC9z+ZHJcA/i59TyjxEPXiiUgN2WmTyV5OEZWCD6gQhgkdpB/" crossorigin="anonymous"></script>
  </head>
  <body hx-headers='{"X-CSRFToken":"{{ csrf_token }}"}'>

    {% include "navbar.html" %}
    {% block content %}
    {% endblock content %}
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/navbar.html
{% load account %}
<nav
  class="navbar navbar-expand-lg bg-body-tertiary rounded"
  aria-label="Thirteenth navbar example"
>
  <div class="container-fluid">
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarsExample11"
      aria-controls="navbarsExample11"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse d-lg-flex" id="navbarsExample11">
      <a class="navbar-brand col-lg-3 me-0" href="#">Recommender</a>
      <ul class="navbar-nav col-lg-6 justify-content-lg-center">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'movies:list' %}">Movies</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'movies:popular' %}">Popular Reviews</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="{% url 'movies:infinite' %}" >Infinite Reviews</a>
        </li>
      </ul>
      <div class="d-lg-flex col-lg-3 justify-content-lg-end">
        {% if user.is_authenticated %}
        <div class="dropdown">
          <button
            class="btn btn-secondary fw-bold dropdown-toggle"
            type="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            {% user_display user %}
          </button>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'account_email' %}">Email</a></li>
            <li><a class="dropdown-item" href="{% url 'account_change_password' %}">Change Password</a></li>
            <li><a class="dropdown-item btn btn-danger" href="{% url 'account_logout' %}">Log out</a></li>
          </ul>
        </div>
        {% else %}

        <a href="{% url 'account_signup' %}" class="btn btn-outline-dark w-50">Sign Up</a>
        <a href="{% url 'account_login' %}" class="btn btn-dark w-50">Login</a>
        {% endif %}
      </div>
    </div>
  </div>
</nav>